version: '3.8'

services:
  db:
    image: postgres:15
    container_name: researchchat_postgres
    environment:
      POSTGRES_DB: researchchat_db
      POSTGRES_USER: chattruser
      POSTGRES_PASSWORD: chattrpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
